# Generated by Django 2.0.2 on 2018-04-24 00:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_auto_20180424_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 24, 0, 14, 18, 433786, tzinfo=utc)),
        ),
    ]
